### ISSUE TITLE
Некорректное отображение результатов запроса

### ISSUE THREAD

**Issue by KirillFurtikov** [yamax2/rubrics#19]
Когда обновили/создали/отредактировали/удалили рубрику выводится сообщение `Record was successfully *.` но не сразу после действия, а при переходе на главную страницу.
Сообщение должно отображаться сразу, как только действие выполнилось.
![msg](https://user-images.githubusercontent.com/21662650/28570594-412205e4-7158-11e7-8337-79652fb7402d.gif)

**Comment by yamax2** [comment]
:+1:  поправим отдельным реквестом
